# Shape and Reshape


## shape

O atributo [*shape*](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.shape.html#numpy-ndarray-shape) é uma tupla representando as dimensões do ndarray e pode ser utilizado para redimensioná-lo


### Usando shape para obter as dimensões do array

In [6]:
import numpy

my_1D_array = numpy.array([1, 2, 3, 4, 5])
print(my_1D_array.shape)    #(5,) -> 5 linhas e 0 colunas

my_2D_array = numpy.array([[1, 2],[3, 4],[6,5]])
print(my_2D_array.shape)     #(3, 2) -> 3 linhas e 2 colunas 

(5,)
(3, 2)


### Usando *shape* para redimensionar um array

In [5]:
import numpy

change_array = numpy.array([1,2,3,4,5,6])
change_array.shape = (3, 2)
change_array

array([[1, 2],
       [3, 4],
       [5, 6]])

## reshape

O método *reshape* dá um novo formato (*shape*) ao array sem modificar seus dados. Ele cria um novo array e não modifica o original. 

In [19]:
import numpy

my_array = numpy.array([1,2,3,4,5,6])
print("reshape: ")
print(numpy.reshape(my_array,(3,2)))
print('-------')
print(my_array.reshape(3,2))
print('')
print("Array original: ")
print(my_array)

reshape: 
[[1 2]
 [3 4]
 [5 6]]
-------
[[1 2]
 [3 4]
 [5 6]]

Array original: 
[1 2 3 4 5 6]


## Tarefa

A você será dado uma sequência de inteiros separados por espaço. Sua tarefa é converter essa sequência em um NumPy array 3x3.

### Formato de Entrada

Uma única linha com uma sequência de inteiros separados por espaço

### Formato de Saída

Imprima um NumPy array 3x3.

### Exemplo de Entrada 0

```
1 2 3 4 5 6 7 8 9
```

### Exemplo de Saída 0

```
[[1 2 3]
 [4 5 6]
 [7 8 9]]
```

## Submissão do Código

Para submissão e codificação da tarefa utilizar o link a seguir: https://www.hackerrank.com/contests/ead-vetorizacao-com-numpy/challenges/np-shape-reshape. Essa paǵina é apenas a tradução das instruções do link anterior.