# Transposta e Achatamento

## Transposta

Nós podemos gerar um transposta de arra usando o método [```numpy.transpose```](https://docs.scipy.org/doc/numpy/reference/generated/numpy.transpose.html#numpy-transpose). Seu efeito não afetará o array original, mas criará um novo array.

In [3]:
import numpy

my_array = numpy.array([[1,2,3],
                        [4,5,6]])
print(numpy.transpose(my_array))

[[1 4]
 [2 5]
 [3 6]]


## Achatamento (Flatten)

O método [```flatten```](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.flatten.html) cria uma cópia do array de entrada "achatando-o" em uma dimensão.

In [4]:
import numpy

my_array = numpy.array([[1,2,3],
                        [4,5,6]])
print my_array.flatten()

[1 2 3 4 5 6]


## Tarefa

A você será dado um array 2d com dimensões NxM com os elementos separados por espaço (N = número de linhas e M = número de colunas). Sua tarefa é imprimir a transposta e versão 1d da matriz.

### Formato de Entrada

A primeira linha contém dois inteiros, N e M, separados por espaço.
Cada uma das próximas N linhas contém M elementos separados por espaço.

### Formato de Saída

Primeiro imprima a transposta e , em seguida, imprima a versão 1d.

### Exemplo de Entrada

```
2 2
1 2
3 4
```

### Exemplo de Saída

```
[[1 3]
 [2 4]]
[1 2 3 4]
```

## Submissão do Código

Para submissão e codificação da tarefa utilizar o link a seguir:https://www.hackerrank.com/contests/ead-vetorizacao-com-numpy/challenges/np-transpose-and-flatten. Essa paǵina é apenas a tradução das instruções do link anterior.