# Concatenação

Dois ou mais arrays podem ser concatenados usando a função [```concatenate```](https://docs.scipy.org/doc/numpy/reference/generated/numpy.concatenate.html) com a tupla de arrays a serem combinados:

In [1]:
import numpy

array_1 = numpy.array([1,2,3])
array_2 = numpy.array([4,5,6])
array_3 = numpy.array([7,8,9])

numpy.concatenate((array_1, array_2, array_3))  

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Se um array possui mais de uma dimensão, é possível especificar qual o eixo (dimensão) os arrays serão concatenados. Por padrão, o eixo é o primeiro (o das linhas).

In [6]:
import numpy

array_1 = numpy.array([[1,2,3],[0,0,0]])
array_2 = numpy.array([[0,0,0],[7,8,9]])

print("Padrão é axis = 0 : ")
print(numpy.concatenate((array_1, array_2)))
print('')
print("Axis = 1 : ")
print(numpy.concatenate((array_1, array_2), axis = 1))

Padrão é axis = 0 : 
[[1 2 3]
 [0 0 0]
 [0 0 0]
 [7 8 9]]

Axis = 1 : 
[[1 2 3 0 0 0]
 [0 0 0 7 8 9]]


## Tarefa

A você será dado dois arrays de inteiros de tamanhos $NxP$ e $MxP$ ($N$ e $M$ são número de linhas de cada array, e $P$ o número de colunas). Sua missão é concatenar os arrays pelo eixo 0.

### Formato de Entrada

A primeira linha contém os inteiros $N$,$M$ e $P$ separados por espaço.
As próximas N linhas contém P elementos separados por espaço.
Após as N linhas, haverá mais M linhas cada uma das quais contendo P elementos separados por espaço.

### Formato de Saída

Imprima a matriz resultante da concatenação, ela deve ter tamanho $(N + M)xP$

### Exemplo de Entrada

```
4 3 2
1 2
1 2 
1 2
1 2
3 4
3 4
3 4 
```

### Exemplo de Saída 

```
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]
```

## Submissão do Código

Para submissão e codificação da tarefa utilizar o link a seguir:https://www.hackerrank.com/contests/ead-vetorizacao-com-numpy/challenges/np-concatenate. Essa paǵina é apenas a tradução das instruções do link anterior.