# Zeros e Uns


## Zeros

O método [```zeros```](https://docs.scipy.org/doc/numpy/reference/generated/numpy.zeros.html#numpy-zeros) retorna um novo array preenchido com 0's com a dimensão informada por uma tupla.

In [1]:
import numpy

numpy.zeros((1,2))                    #Tipo padrão é float

array([[ 0.,  0.]])

In [2]:
numpy.zeros((1,2), dtype = numpy.int) #Tipo trocado para int

array([[0, 0]])

## Uns

O método [```ones```](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html#numpy-ones) retorna um novo array preenchido com 1's com a dimensão informada por uma tupla.

In [4]:
import numpy

numpy.ones((1,2))                    #Tipo padrão é float

array([[ 1.,  1.]])

In [5]:
numpy.ones((1,2), dtype = numpy.int) #Tipo trocado para int

array([[1, 1]])

## Tarefas

A você será dado as dimensões do array na forma de inteiros separados por espaço, cada inteiro representando o tamanho de uma dimensão distinta. Sua tarefa é imprimir um array com as dimensões informadas, utilizando os métodos [```numpy.zeros```]() e ```numpy.ones```.

### Formato de Entrada

Uma linha contendo inteiros separados por espaço.

### Restrições

O valores dos inteiros na primeira linha pode variar de 1 a 3 (ambos inclusos). Note que pode a quantidade de números inteiros é indefinida, ou seja, a array pode ter várias dimensões (por exemplo, o array poderia ter 20 dimensões).

### Formato de Saída

Primeiro, imprima o array criado com ```numpy.zeros``` e, então, imprima array criado com ```numpy.ones```.

### Exemplo de Entrada

```
3 3 3
```

### Exemplo de Saída 

```
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]
```

## Passos para resolução

1) Receba os números que representarão a dimensão da matriz a ser gerada;

2) Gere uma "tupla" com a dimensão informada (no exemplo: 3x3x3, mas lembre-se que o problema não está limitado a 3 dimensões);

3) Imprima uma matriz com a dimensão informada preenchida com "zeros" e outra com "uns".

## Submissão do Código

Para submissão e codificação da tarefa utilizar o link a seguir: https://www.hackerrank.com/contests/ead-vetorizacao-com-numpy/challenges/np-zeros-and-ones. Essa paǵina é apenas a tradução das instruções do link anterior.