# Array Mathematics

Operações matemáticas básicas são funcionam elemento a elemento em ndarrays. Elas estão disponíveis tanto com operadores sobrecarregados quanto como funções.

In [1]:
import numpy

a = numpy.array([1,2,3,4], float)
b = numpy.array([5,6,7,8], float)

print a + b                     #[  6.   8.  10.  12.]
print numpy.add(a, b)           #[  6.   8.  10.  12.]

print a - b                     #[-4. -4. -4. -4.]
print numpy.subtract(a, b)      #[-4. -4. -4. -4.]

print a * b                     #[  5.  12.  21.  32.]
print numpy.multiply(a, b)      #[  5.  12.  21.  32.]

print a / b                     #[ 0.2         0.33333333  0.42857143  0.5       ]
print numpy.divide(a, b)        #[ 0.2         0.33333333  0.42857143  0.5       ]

print a % b                     #[ 1.  2.  3.  4.]
print numpy.mod(a, b)           #[ 1.  2.  3.  4.]

print a**b                      #[  1.00000000e+00   6.40000000e+01   2.18700000e+03   6.55360000e+04]
print numpy.power(a, b)         #[  1.00000000e+00   6.40000000e+01   2.18700000e+03   6.55360000e+04]

[  6.   8.  10.  12.]
[  6.   8.  10.  12.]
[-4. -4. -4. -4.]
[-4. -4. -4. -4.]
[  5.  12.  21.  32.]
[  5.  12.  21.  32.]
[ 0.2         0.33333333  0.42857143  0.5       ]
[ 0.2         0.33333333  0.42857143  0.5       ]
[ 1.  2.  3.  4.]
[ 1.  2.  3.  4.]
[  1.00000000e+00   6.40000000e+01   2.18700000e+03   6.55360000e+04]
[  1.00000000e+00   6.40000000e+01   2.18700000e+03   6.55360000e+04]


## Tarefa

A você é dado dois arrays ($A$ e $B$) de mesma dimensões ($NxM$)

1. A + B
2. A - B
3. A * B
4. A // B
5. A % B
6. A \*\* B

### Formato de Entrada

A primeira linha contém os inteiros N e M separados por espaço. As próximas N linhas contém M elementos separados por espaço do array A. Após as N linhas, haverá mais N linhas cada uma das quais contendo M elementos separados por espaço do array B.

### Formato de Saída

Imprima o resultado das operações na ordem estabelecida na tarefa.

### Exemplo de Entrada
```
1 4
1 2 3 4
5 6 7 8
``` 

### Exemplo de Saída

```
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]] 
```
 
Use **//** para divisão em Python 3.

## Submissão do Código

Para submissão e codificação da tarefa utilizar o link a seguir: https://www.hackerrank.com/contests/ead-vetorizacao-com-numpy/challenges/np-array-mathematics. Essa paǵina é apenas a tradução das instruções do link anterior.