# Módulos

Um módulo refere-se a um arquivo contendo definições de funções e intruções Python.

Um arquivo contendo um código Python, por exemplo: exemplo.py, é chamado de modulo e seu nome seria exemplo.

Módulos ajudando a tornar o código, a medida que vai crescendo, mais organizado e manutenível. Alémdisso, modulos promovem a reusabilidade do código.

Python possui vários modulos embutidos na linguagem. Um deles é ```math```. Vamos ver como utilizar as funçòes e definições de modulo.

Primeiro, nós temos de importar o modulo. Para isso, é utilizado o comando ```import```. 

In [4]:
# importamos o modulo
import math

# vamos utilzar a função sqrt e log
print(math.sqrt(4))
print(math.log(10))

2.0
2.30258509299


Nos podemos importar a propria função a partir de um modulo, sem a necessidade de escrever toda vez o nome do mesmo.

In [6]:
# importamos o modulo
from math import sqrt, log

# vamos utilzar a função sqrt e log
print(sqrt(4))
print(log(10))

2.0
2.30258509299


## Renomear importação

Podemos renomear as funções e modolos que importamos, utilizando a claúsula ```as```.

In [9]:
import math as m
# log em python é logaritmo natural e nao na base 10
from math import log as ln

# vamos utilzar a função sqrt e log
print(m.sqrt(4))
print(ln(10))

2.0
2.30258509299


### Importando tudo em um modulo

In [11]:
from math import *

print(sqrt(4))
print(log(10))

2.0
2.30258509299


## Exercício

Muitas vezes quando estamos criando nossos modelos é preciso definir uma métrica para nós os avaliarmos e escolher o melhor dentre eles. Algumas vezes, nós mesmo temos de implementá-las, portanto, nesse exercício você vai ter de implementar uma extensão da métrica Erro Quadrático Médio, em inglês *Mean Squared Error (MSE)*, chamada *Root Mean Squared Logarithmic Error (RMSLE)*. 

A RMSLE é deifnida como:

$\epsilon = \sqrt{\frac{1}{n}\sum_{i=1}^{n}(\log(\hat{y}_i) - \log(y_i))^2}$

onde:

- $\epsilon$ é o valor do erro (score)
- $n$ é o total de exemplos no conjunto de dados testado
- $\hat{y}_i$ é a predição do modelo
- $y_i$ é o valor do real do imóvel (rótulo)
- $\log(x)$ é a função logarítmica de $x$

A RMSLE penaliza mais estimativas erradas para menos do que para mais.

In [45]:
def RMSLE(y_true, y_pred):
    """ Root Mean Squared Logarithmic Error 
    Parâmetros
    ----------
    y_true : 1d array
        Rótulos.
    y_pred : 1d array
        Predições, retornadas pelo modelo.
    """
    # TODO: seu código
    pass

# criando uma entrada exemplo
y_true =  [1, 2, 3, 4, 5, 6, 7, 8, 9]
y_pred = map(lambda y: 0.9 * y if y % 2 else 1.2 * y, y_true)

# saida esperada : 0.14470997492513551
print(RMSLE(y_true, y_pred))

None


## Criando um módulo

Um módulo é apenas um arquivo *.py*. Todas as funções criadas nesse arquivo pode ser acessadas utilizando o import.

Crie um arquivo meu_modulo.py e copie e cole a função RMSLE recém criada lá. O código a abaixo deveria funcionar.

In [5]:
from meu_modulo import RMSLE

y_true =  [1, 2, 3, 4, 5, 6, 7, 8, 9]
y_pred = map(lambda y: 0.9 * y if y % 2 else 1.2 * y, y_true)

# saida esperada : 0.14470997492513551
print(RMSLE(y_true, y_pred))

0.144709974925


# Pacotes

Em nosso computador, nós não armazenamos todos nossos arquivos em um único lugar. Nós os organizamos hierarquicamente em diretórios para que possamos acessá-los rapidamente.

Analogamente a isso, Python em python nós organizamos nossos modulos em pacotes.

A medida que nossa aplicação cresce com um monte de módulos, nós agrupamos modulos similares em um pacote e módulos distintos em pacotes diferentes.

Abaixo uma pequena amostra da organização do pacote numpy que iremos utilizar bastantes nesse curso.

![pacote](package-example.png)

## Importando de pacotes

In [38]:
import numpy.random as random

random.uniform(0, 1, 3)

array([ 0.48724739,  0.43546647,  0.71773515])

In [39]:
from numpy.random import uniform

uniform(0, 1, 3)

array([ 0.76758684,  0.6138424 ,  0.6295583 ])

In [40]:
import numpy as np

np.random.uniform(0, 1, 3)

array([ 0.94946036,  0.8892111 ,  0.87754829])