# Concatenação



In [2]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.arange(7, 10)

print("a : ", a)
print("b : ", b)
print("c :", c)

a :  [1 2 3]
b :  [4 5 6]
c : [7 8 9]


In [ ]:
print(np.concatenate((a,b)))
print(np.concatenate((b,a)))

In [ ]:
print(np.concatenate((a, b, c)))

## Concatenando matrizes 

In [3]:
a = np.floor(10*np.random.random((2,2)))

print(a)

b = np.floor(10*np.random.random((2,2)))

print(b)

[[8. 9.]
 [7. 2.]]
[[3. 9.]
 [6. 4.]]


In [4]:
# equivale ao np.vstack((a, b))
print(np.concatenate((a,b), axis=0))

# equivale ao np.hstack((a, b))
print(np.concatenate((a,b), axis=1))

[[8. 9.]
 [7. 2.]
 [3. 9.]
 [6. 4.]]
[[8. 9. 3. 9.]
 [7. 2. 6. 4.]]


In [ ]:
print(np.vstack((a, b)))

print(np.hstack((a, b)))

# Cópias

Nunca é criado uma cópia do array implicitamente.

In [ ]:
a = np.arange(12)

b = a

# a e b são o mesma instanância
print(b is a, id(b), id(a)) 

b.shape = 3,4 # muda a
a.shape

Python passa objetos mutaveis como referência, portanto a chamada de uma função não faz cópia.

In [ ]:
def f(x):
    print(id(x))
    
print(id(a))
f(a)

Sclicing retorna uma view do array. Views são novos objetos do tipo ndarray que apontam para o mesmo dado.

In [ ]:
s = a[:, 1:3]    
s[:] = 10      
a

Portanto, é necessário fazer cópias explicitamente (quando desejado) através do método ```copy```.

In [ ]:
# um novo objeto com um novo data é criado
d = a.copy()       

print(d is a)
# não compartilha nada com a
print(d.base is a)

d[0,0] = 9999
a